import{describe,it,expect}from'vitest';
import{readFileSync}from'node:fs';
import{beginContactSubmission,canStartContactSubmission,clearTurnstileErrorOnToken,contactStatus,contactSubmissionFailed,contactSubmissionSucceeded,contactTurnstileFailed}from'../src/lib/contact-submission.js';

describe('Contact submission status',()=>{
  it('shows only an error after a failed submission',()=>{const status=contactSubmissionFailed('Message could not be sent. Please check the details and try again.');expect(status).toEqual({phase:'error',message:'Message could not be sent. Please check the details and try again.',kind:'submission'});expect(status.phase).not.toBe('success')});
  it('clears a previous error when a retry succeeds',()=>{const previous=contactSubmissionFailed('Old error'),status=contactSubmissionSucceeded();expect(previous.phase).toBe('error');expect(status).toEqual({phase:'success',message:'Thank you. Your enquiry has been submitted successfully.',kind:''})});
  it('shows only success after a successful submission',()=>{const status=contactSubmissionSucceeded();expect(status.phase).toBe('success');expect(status.message).toContain('submitted successfully');expect(status.kind).toBe('')});
  it('clears previous success when a new submission starts',()=>{const status=beginContactSubmission(contactSubmissionSucceeded());expect(status).toEqual({phase:'submitting',message:'',kind:''})});
  it('clears an obsolete Turnstile error when a token later arrives',()=>{const error=contactSubmissionFailed('Verification could not load. Please try again.','turnstile');expect(clearTurnstileErrorOnToken(error,'new-token')).toEqual(contactStatus());expect(clearTurnstileErrorOnToken(error,'')).toEqual(error)});
  it('does not replace a confirmed success with a late Turnstile error',()=>{const success=contactSubmissionSucceeded();expect(contactTurnstileFailed(success,'Verification could not load.')).toEqual(success)});
  it('has exactly one mutually exclusive status message',()=>{for(const status of[contactStatus(),beginContactSubmission(),contactSubmissionFailed('No'),contactSubmissionSucceeded()]){expect(['idle','submitting','error','success']).toContain(status.phase);if(status.message)expect(status.phase).toMatch(/error|success/);else expect(status.phase).toMatch(/idle|submitting/);expect(status.phase==='error'&&status.phase==='success').toBe(false)}});
  it('prevents duplicate submissions while loading',()=>{expect(canStartContactSubmission(beginContactSubmission())).toBe(false);expect(canStartContactSubmission(contactSubmissionFailed('Retry'))).toBe(true)});
  it('resets form fields only on the successful request path and renders one status region',()=>{const source=readFileSync('src/main.jsx','utf8'),success=source.indexOf('setStatus(contactSubmissionSucceeded());form.reset()'),failure=source.indexOf('}catch(reason){setStatus(contactSubmissionFailed(');expect(success).toBeGreaterThan(-1);expect(failure).toBeGreaterThan(success);expect(source).toContain("{status.message&&<p className={`form-status ${status.phase}`} role={status.phase==='error'?'alert':'status'}")});
});
