import{afterEach,beforeEach,describe,it,expect,vi}from'vitest';
import request from'supertest';
import bcrypt from'bcryptjs';
import os from'node:os';
import fs from'node:fs/promises';
import path from'node:path';

const execute=vi.fn();
vi.mock('../server/config/db.js',()=>({db:()=>({execute})}));
process.env.SESSION_SECRET='test-session-secret-at-least-32-characters';
const{createApp}=await import('../server/app.js');
const image=Buffer.from('not-a-real-image-but-valid-for-multer-mime-tests');
let app,root;

beforeEach(async()=>{execute.mockReset();global.fetch=vi.fn();root=await fs.mkdtemp(path.join(os.tmpdir(),'sampark-h1a-'));app=createApp({uploadRoot:root})});
afterEach(async()=>fs.rm(root,{recursive:true,force:true}));

const adminRecord=async()=>({id:1,email:'admin@test.org',password_hash:await bcrypt.hash('strong-password-123',4)});
const login=async()=>{execute.mockResolvedValueOnce([[await adminRecord()]]);const response=await request(app).post('/api/auth/login').send({email:'admin@test.org',password:'strong-password-123'});expect(response.status).toBe(200);return response.headers['set-cookie'][0]};
const authenticated=async()=>({cookie:await login(),allow:()=>execute.mockResolvedValueOnce([[{id:1}]])});
const publicFile=(kind,name)=>`uploads/${kind}/${name}`;
const physical=(kind,name)=>path.join(root,kind,name);
const physicalStored=stored=>path.join(root,stored.replace(/^uploads[\\/]/,''));
const seed=async(kind,name)=>{await fs.writeFile(physical(kind,name),image);return publicFile(kind,name)};
const galleryFields=requestBuilder=>requestBuilder.field('title','Gallery title').field('description','Description').field('event_date','2026-01-01').field('display_order','2').field('active','1');
const memberFields=requestBuilder=>requestBuilder.field('name','Member name').field('designation','Volunteer').field('bio','Biography').field('display_order','2').field('active','1');
const storedFromLastCall=()=>execute.mock.calls.findLast(([sql])=>/^(insert into|update )/i.test(sql))[1][5];

describe('H1A Express routes',()=>{
  it('creates managed directories under a custom upload root',async()=>{expect((await fs.stat(path.join(root,'gallery'))).isDirectory()).toBe(true);expect((await fs.stat(path.join(root,'members'))).isDirectory()).toBe(true)});
  it('issues signed HttpOnly cookie',async()=>expect(await login()).toMatch(/HttpOnly/));
  it('rejects invalid credentials',async()=>{execute.mockResolvedValueOnce([[]]);expect((await request(app).post('/api/auth/login').send({email:'x@y.z',password:'bad'})).status).toBe(401)});
  it('rejects anonymous admin access',async()=>expect((await request(app).get('/api/admin/donations')).status).toBe(401));
  it('allows valid signed admin cookie',async()=>{const c=await login();execute.mockResolvedValueOnce([[{id:1}]]);expect((await request(app).get('/api/auth/me').set('Cookie',c)).status).toBe(200)});
  it('returns 404 for missing gallery and member update with one cookie',async()=>{const c=await login();execute.mockResolvedValueOnce([[{id:1}]]).mockResolvedValueOnce([[]]);expect((await request(app).put('/api/admin/gallery/999').set('Cookie',c).send({title:'x'})).status).toBe(404);execute.mockResolvedValueOnce([[{id:1}]]).mockResolvedValueOnce([[]]);expect((await request(app).put('/api/admin/members/999').set('Cookie',c).send({name:'x'})).status).toBe(404)});
  it('fails closed on invalid Turnstile',async()=>{global.fetch.mockResolvedValueOnce({ok:true,json:async()=>({success:false})});const response=await request(app).post('/api/contact').send({name:'A',email:'a@b.co',subject:'s',message:'m',turnstile_token:'x'});expect(response.status).toBe(400);expect(execute).not.toHaveBeenCalled()});
  it('inserts after verified Turnstile only',async()=>{global.fetch.mockResolvedValueOnce({ok:true,json:async()=>({success:true})});execute.mockResolvedValueOnce([{}]);expect((await request(app).post('/api/contact').send({name:'A',email:'a@b.co',subject:'s',message:'m',turnstile_token:'x'})).status).toBe(201);expect(execute).toHaveBeenCalledTimes(1)});
  it('returns protected full admin gallery and member records',async()=>{const cookie=await login();execute.mockResolvedValueOnce([[{id:1}]]).mockResolvedValueOnce([[{id:2,active:0}]]);expect((await request(app).get('/api/admin/gallery').set('Cookie',cookie)).body).toEqual([{id:2,active:0}]);execute.mockResolvedValueOnce([[{id:1}]]).mockResolvedValueOnce([[{id:3,active:0}]]);expect((await request(app).get('/api/admin/members').set('Cookie',cookie)).body).toEqual([{id:3,active:0}])});

  it('gallery multipart create stores a generated public path and file',async()=>{const{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([{insertId:11}]);const response=await galleryFields(request(app).post('/api/admin/gallery').set('Cookie',cookie)).attach('image',image,{filename:'client-name.png',contentType:'image/png'});expect(response.status).toBe(201);const stored=storedFromLastCall();expect(stored).toMatch(/^uploads\/gallery\/[0-9a-f-]+\.png$/);await expect(fs.stat(physicalStored(stored))).resolves.toBeDefined();expect(stored).not.toContain('client-name')});
  it('gallery metadata update retains the existing managed image',async()=>{const old=await seed('gallery','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,title:'Old',description:'Old',event_date:'2025-01-01',display_order:1,active:1,image_path:old}]]).mockResolvedValueOnce([{}]);const response=await request(app).put('/api/admin/gallery/2').set('Cookie',cookie).send({title:'New'});expect(response.status).toBe(200);expect(storedFromLastCall()).toBe(old);await expect(fs.stat(physical('gallery','old.png'))).resolves.toBeDefined()});
  it('gallery image replacement writes new then removes old after update',async()=>{const old=await seed('gallery','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,title:'Old',description:'Old',event_date:'2025-01-01',display_order:1,active:1,image_path:old}]]).mockResolvedValueOnce([{}]);const response=await galleryFields(request(app).put('/api/admin/gallery/2').set('Cookie',cookie)).attach('image',image,{filename:'new.webp',contentType:'image/webp'});expect(response.status).toBe(200);const stored=storedFromLastCall();expect(stored).toMatch(/^uploads\/gallery\/[0-9a-f-]+\.webp$/);await expect(fs.stat(physicalStored(stored))).resolves.toBeDefined();await expect(fs.stat(physical('gallery','old.png'))).rejects.toMatchObject({code:'ENOENT'})});
  it('gallery DB failure cleans the new orphan and preserves the old image',async()=>{const old=await seed('gallery','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,title:'Old',description:'Old',event_date:'2025-01-01',display_order:1,active:1,image_path:old}]]).mockRejectedValueOnce(Error('db failure'));const response=await galleryFields(request(app).put('/api/admin/gallery/2').set('Cookie',cookie)).attach('image',image,{filename:'new.png',contentType:'image/png'});expect(response.status).toBe(400);await expect(fs.stat(physical('gallery','old.png'))).resolves.toBeDefined();expect((await fs.readdir(path.join(root,'gallery')))).toEqual(['old.png'])});
  it('gallery delete cleans its managed image',async()=>{const old=await seed('gallery','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,image_path:old}]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/gallery/2').set('Cookie',cookie)).status).toBe(204);await expect(fs.stat(physical('gallery','old.png'))).rejects.toMatchObject({code:'ENOENT'})});
  it('gallery deletion safely handles a missing managed file',async()=>{const{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,image_path:publicFile('gallery','missing.png')}]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/gallery/2').set('Cookie',cookie)).status).toBe(204)});
  it('gallery cleanup cannot delete a crafted path outside its managed root',async()=>{const outside=path.join(root,'outside.png');await fs.writeFile(outside,image);const{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,image_path:'../../outside.png'}]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/gallery/2').set('Cookie',cookie)).status).toBe(204);await expect(fs.stat(outside)).resolves.toBeDefined()});

  it('member multipart create stores a generated public path and file',async()=>{const{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([{insertId:12}]);const response=await memberFields(request(app).post('/api/admin/members').set('Cookie',cookie)).attach('image',image,{filename:'client-name.jpg',contentType:'image/jpeg'});expect(response.status).toBe(201);const stored=storedFromLastCall();expect(stored).toMatch(/^uploads\/members\/[0-9a-f-]+\.jpg$/);await expect(fs.stat(physicalStored(stored))).resolves.toBeDefined();expect(stored).not.toContain('client-name')});
  it('member metadata update retains the existing managed photo',async()=>{const old=await seed('members','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,name:'Old',designation:'Old',bio:'Old',display_order:1,active:1,photo_path:old}]]).mockResolvedValueOnce([{}]);const response=await request(app).put('/api/admin/members/2').set('Cookie',cookie).send({name:'New'});expect(response.status).toBe(200);expect(storedFromLastCall()).toBe(old);await expect(fs.stat(physical('members','old.png'))).resolves.toBeDefined()});
  it('member photo replacement writes new then removes old after update',async()=>{const old=await seed('members','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,name:'Old',designation:'Old',bio:'Old',display_order:1,active:1,photo_path:old}]]).mockResolvedValueOnce([{}]);const response=await memberFields(request(app).put('/api/admin/members/2').set('Cookie',cookie)).attach('image',image,{filename:'new.webp',contentType:'image/webp'});expect(response.status).toBe(200);const stored=storedFromLastCall();expect(stored).toMatch(/^uploads\/members\/[0-9a-f-]+\.webp$/);await expect(fs.stat(physicalStored(stored))).resolves.toBeDefined();await expect(fs.stat(physical('members','old.png'))).rejects.toMatchObject({code:'ENOENT'})});
  it('member DB failure cleans the new orphan and preserves the old photo',async()=>{const old=await seed('members','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,name:'Old',designation:'Old',bio:'Old',display_order:1,active:1,photo_path:old}]]).mockRejectedValueOnce(Error('db failure'));const response=await memberFields(request(app).put('/api/admin/members/2').set('Cookie',cookie)).attach('image',image,{filename:'new.png',contentType:'image/png'});expect(response.status).toBe(400);await expect(fs.stat(physical('members','old.png'))).resolves.toBeDefined();expect((await fs.readdir(path.join(root,'members')))).toEqual(['old.png'])});
  it('member delete cleans its managed photo',async()=>{const old=await seed('members','old.png'),{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,photo_path:old}]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/members/2').set('Cookie',cookie)).status).toBe(204);await expect(fs.stat(physical('members','old.png'))).rejects.toMatchObject({code:'ENOENT'})});
  it('member deletion safely handles a missing managed photo',async()=>{const{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,photo_path:publicFile('members','missing.png')}]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/members/2').set('Cookie',cookie)).status).toBe(204)});
  it('member cleanup cannot delete a crafted path outside its managed root',async()=>{const outside=path.join(root,'outside.png');await fs.writeFile(outside,image);const{cookie,allow}=await authenticated();allow();execute.mockResolvedValueOnce([[{id:2,photo_path:'../../outside.png'}]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/members/2').set('Cookie',cookie)).status).toBe(204);await expect(fs.stat(outside)).resolves.toBeDefined()});
});
