import{describe,it,expect,vi}from'vitest';
import{readFileSync}from'node:fs';
import{AdminApiError,adminRequest,publicImageUrl}from'../src/lib/api.js';

const response=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});

describe('H3 admin API client',()=>{
  it('uses Express login and includes credentials without storing tokens',async()=>{const fetcher=vi.fn().mockResolvedValue(response({id:1,email:'admin@example.org'}));await expect(adminRequest('/api/auth/login',{method:'POST',body:{email:'admin@example.org',password:'secret'},fetcher,base:''})).resolves.toEqual({id:1,email:'admin@example.org'});expect(fetcher).toHaveBeenCalledWith('/api/auth/login',expect.objectContaining({method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@example.org',password:'secret'})}))});
  it('checks /me and handles an expired session safely',async()=>{await expect(adminRequest('/api/auth/me',{fetcher:vi.fn().mockResolvedValue(response({id:1,email:'admin@example.org'}))})).resolves.toMatchObject({id:1});await expect(adminRequest('/api/auth/me',{fetcher:vi.fn().mockResolvedValue(response({},401))})).rejects.toMatchObject({status:401})});
  it('logs out through Express with credentials included',async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,status:204});await expect(adminRequest('/api/auth/logout',{method:'POST',fetcher})).resolves.toBeNull();expect(fetcher).toHaveBeenCalledWith('/api/auth/logout',expect.objectContaining({method:'POST',credentials:'include'}))});
  it('uses protected Express reads for gallery, members, programs, messages, and donations',async()=>{const fetcher=vi.fn().mockResolvedValue(response([]));for(const route of ['/api/admin/gallery','/api/admin/members','/api/admin/programs','/api/admin/contact-messages','/api/admin/donations','/api/admin/donations/summary'])await expect(adminRequest(route,{fetcher})).resolves.toEqual([]);expect(fetcher.mock.calls.every(([,options])=>options.credentials==='include')).toBe(true)});
  it('sends gallery, member, and program creates or updates as FormData without a manual multipart header',async()=>{const body=new FormData();body.append('title','Title');body.append('image',new Blob(['image'],{type:'image/png'}),'photo.png');const fetcher=vi.fn().mockResolvedValue(response({id:1}));for(const route of ['/api/admin/gallery','/api/admin/gallery/1','/api/admin/members','/api/admin/members/1','/api/admin/programs','/api/admin/programs/1'])await adminRequest(route,{method:route.endsWith('/1')?'PUT':'POST',body,fetcher});for(const[,options]of fetcher.mock.calls){expect(options.credentials).toBe('include');expect(options.headers).toEqual({});expect(options.body).toBe(body)}});
  it('uses protected Express delete routes',async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,status:204});await adminRequest('/api/admin/gallery/1',{method:'DELETE',fetcher});await adminRequest('/api/admin/members/1',{method:'DELETE',fetcher});expect(fetcher.mock.calls.map(([url])=>url)).toEqual(['/api/admin/gallery/1','/api/admin/members/1'])});
  it('maps API failures to typed safe errors',async()=>{await expect(adminRequest('/api/admin/gallery',{fetcher:vi.fn().mockRejectedValue(Error('network details'))})).rejects.toBeInstanceOf(AdminApiError);await expect(adminRequest('/api/admin/members',{fetcher:vi.fn().mockResolvedValue(response({},413))})).rejects.toMatchObject({status:413})});
  it('uses the shared relative image resolver for admin previews',()=>expect(publicImageUrl('uploads/members/a.png','https://api.example.org')).toBe('https://api.example.org/uploads/members/a.png'));
  it('contains no retired backend client or browser token calls in the admin path',()=>{const admin=readFileSync('src/admin.jsx','utf8');expect(admin).not.toMatch(/localStorage|sessionStorage|\.storage\./i)});
});
