import{afterEach,beforeEach,describe,it,expect,vi}from'vitest';
import request from'supertest';
import bcrypt from'bcryptjs';
import os from'node:os';
import fs from'node:fs/promises';
import path from'node:path';

const execute=vi.fn();
vi.mock('../server/config/db.js',()=>({db:()=>({execute})}));
process.env.SESSION_SECRET='h7-test-session-secret-at-least-32-characters';
const{createApp}=await import('../server/app.js');
const image=Buffer.from('program-image');
let app,root;
const originalUploadRoot=process.env.UPLOAD_ROOT;

beforeEach(async()=>{execute.mockReset();delete process.env.UPLOAD_ROOT;root=await fs.mkdtemp(path.join(os.tmpdir(),'sampark-h7-'));app=createApp({uploadRoot:root})});
afterEach(async()=>{if(originalUploadRoot===undefined)delete process.env.UPLOAD_ROOT;else process.env.UPLOAD_ROOT=originalUploadRoot;await fs.rm(root,{recursive:true,force:true})});
const login=async()=>{execute.mockResolvedValueOnce([[{id:1,email:'admin@test.org',password_hash:await bcrypt.hash('strong-password-123',4)}]]);return (await request(app).post('/api/auth/login').send({email:'admin@test.org',password:'strong-password-123'})).headers['set-cookie'][0]};
const allow=()=>execute.mockResolvedValueOnce([[{id:1}]]);
const program=builder=>builder.field('title','Community learning').field('short_description','Practical training').field('description','A full program description').field('location','Pune').field('start_date','2026-01-01').field('end_date','2026-12-31').field('status','upcoming').field('display_order','2').field('active','1');
const oldProgram=(image_path='uploads/programs/old.png')=>({id:8,title:'Old',short_description:'Old short',description:'Old description',image_path,location:'Pune',start_date:'2026-01-01',end_date:'2026-02-01',status:'ongoing',display_order:1,active:1});

describe('H7 programs and donation tracking',()=>{
  it('uses the trusted UPLOAD_ROOT for all content types and static delivery',async()=>{const persistentRoot=path.join(root,'persistent-volume');process.env.UPLOAD_ROOT=persistentRoot;app=createApp();const cookie=await login();allow();execute.mockResolvedValueOnce([{insertId:1}]);const gallery=await request(app).post('/api/admin/gallery').set('Cookie',cookie).field('title','Gallery').field('description','Description').field('event_date','2026-01-01').field('display_order','0').field('active','1').attach('image',image,{filename:'gallery.png',contentType:'image/png'});allow();execute.mockResolvedValueOnce([{insertId:2}]);const member=await request(app).post('/api/admin/members').set('Cookie',cookie).field('name','Member').field('designation','Volunteer').field('bio','Biography').field('display_order','0').field('active','1').attach('image',image,{filename:'member.png',contentType:'image/png'});allow();execute.mockResolvedValueOnce([{insertId:3}]);const programResponse=await program(request(app).post('/api/admin/programs').set('Cookie',cookie)).attach('image',image,{filename:'program.png',contentType:'image/png'});expect([gallery.status,member.status,programResponse.status]).toEqual([201,201,201]);const inserts=execute.mock.calls.filter(([sql])=>sql.startsWith('insert into'));const galleryPath=inserts.find(([sql])=>sql.includes('gallery_items'))[1][5],memberPath=inserts.find(([sql])=>sql.includes('members'))[1][5],programPath=inserts.find(([sql])=>sql.includes('programs'))[1][3];for(const stored of[galleryPath,memberPath,programPath])await expect(fs.stat(path.join(persistentRoot,stored.replace(/^uploads\//,'')))).resolves.toBeDefined();const served=await request(app).get(`/${galleryPath}`);expect(served.status).toBe(200);expect(served.body).toEqual(image);const outside=path.join(root,'outside.png');await fs.writeFile(outside,image);allow();execute.mockResolvedValueOnce([[oldProgram('../../outside.png')]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/programs/8').set('Cookie',cookie)).status).toBe(204);await expect(fs.stat(outside)).resolves.toBeDefined()});
  it('lists only active programs in display order and supports an empty public result',async()=>{execute.mockResolvedValueOnce([[{id:2,title:'First'}]]);expect((await request(app).get('/api/programs')).body).toEqual([{id:2,title:'First'}]);expect(execute.mock.calls[0][0]).toMatch(/where active=1 order by display_order,id/);execute.mockResolvedValueOnce([[]]);expect((await request(app).get('/api/programs')).body).toEqual([])});
  it('protects program administration and returns full admin records',async()=>{expect((await request(app).get('/api/admin/programs')).status).toBe(401);const cookie=await login();allow();execute.mockResolvedValueOnce([[{id:2,active:0}]]);expect((await request(app).get('/api/admin/programs').set('Cookie',cookie)).body).toEqual([{id:2,active:0}])});
  it('creates a validated program with a randomized managed image',async()=>{const cookie=await login();allow();execute.mockResolvedValueOnce([{insertId:8}]);const response=await program(request(app).post('/api/admin/programs').set('Cookie',cookie)).attach('image',image,{filename:'untrusted-name.png',contentType:'image/png'});expect(response.status).toBe(201);const values=execute.mock.calls.at(-1)[1];expect(values[3]).toMatch(/^uploads\/programs\/[0-9a-f-]+\.png$/);await expect(fs.stat(path.join(root,values[3].replace(/^uploads\//,'')))).resolves.toBeDefined()});
  it('rejects invalid program fields and invalid image uploads',async()=>{const cookie=await login();allow();expect((await request(app).post('/api/admin/programs').set('Cookie',cookie).send({title:'x',status:'invalid'})).status).toBe(400);allow();expect((await program(request(app).post('/api/admin/programs').set('Cookie',cookie)).attach('image',image,{filename:'bad.gif',contentType:'image/gif'})).status).toBe(400)});
  it('rejects an image larger than the five megabyte limit',async()=>{const cookie=await login();allow();const tooLarge=Buffer.alloc(5*1024*1024+1);const response=await program(request(app).post('/api/admin/programs').set('Cookie',cookie)).attach('image',tooLarge,{filename:'large.png',contentType:'image/png'});expect(response.status).toBe(413)});
  it('updates metadata without replacing the stored image',async()=>{await fs.writeFile(path.join(root,'programs','old.png'),image);const cookie=await login();allow();execute.mockResolvedValueOnce([[oldProgram()]]).mockResolvedValueOnce([{}]);const response=await request(app).put('/api/admin/programs/8').set('Cookie',cookie).send({title:'New title'});expect(response.status).toBe(200);expect(execute.mock.calls.at(-1)[1][3]).toBe('uploads/programs/old.png');await expect(fs.stat(path.join(root,'programs','old.png'))).resolves.toBeDefined()});
  it('replaces an image only after the database update succeeds',async()=>{await fs.writeFile(path.join(root,'programs','old.png'),image);const cookie=await login();allow();execute.mockResolvedValueOnce([[oldProgram()]]).mockResolvedValueOnce([{}]);const response=await program(request(app).put('/api/admin/programs/8').set('Cookie',cookie)).attach('image',image,{filename:'new.webp',contentType:'image/webp'});expect(response.status).toBe(200);await expect(fs.stat(path.join(root,'programs','old.png'))).rejects.toMatchObject({code:'ENOENT'});expect((await fs.readdir(path.join(root,'programs'))).some(name=>name.endsWith('.webp'))).toBe(true)});
  it('cleans a new image on database failure and leaves the old image intact',async()=>{await fs.writeFile(path.join(root,'programs','old.png'),image);const cookie=await login();allow();execute.mockResolvedValueOnce([[oldProgram()]]).mockRejectedValueOnce(Error('database failure'));const response=await program(request(app).put('/api/admin/programs/8').set('Cookie',cookie)).attach('image',image,{filename:'new.png',contentType:'image/png'});expect(response.status).toBe(400);expect(await fs.readdir(path.join(root,'programs'))).toEqual(['old.png'])});
  it('deletes managed files but never follows a path outside programs storage',async()=>{const outside=path.join(root,'outside.png');await fs.writeFile(outside,image);const cookie=await login();allow();execute.mockResolvedValueOnce([[oldProgram('../../outside.png')]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/programs/8').set('Cookie',cookie)).status).toBe(204);await expect(fs.stat(outside)).resolves.toBeDefined();allow();execute.mockResolvedValueOnce([[oldProgram('uploads/programs/missing.png')]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/programs/8').set('Cookie',cookie)).status).toBe(204)});
  it('deletes a managed program image after successful record deletion',async()=>{await fs.writeFile(path.join(root,'programs','old.png'),image);const cookie=await login();allow();execute.mockResolvedValueOnce([[oldProgram()]]).mockResolvedValueOnce([{}]);expect((await request(app).delete('/api/admin/programs/8').set('Cookie',cookie)).status).toBe(204);await expect(fs.stat(path.join(root,'programs','old.png'))).rejects.toMatchObject({code:'ENOENT'})});
  it('returns 404 for a missing program and removes a newly uploaded orphan',async()=>{const cookie=await login();allow();execute.mockResolvedValueOnce([[]]);const response=await program(request(app).put('/api/admin/programs/999').set('Cookie',cookie)).attach('image',image,{filename:'new.png',contentType:'image/png'});expect(response.status).toBe(404);expect(await fs.readdir(path.join(root,'programs'))).toEqual([])});
  it('rejects anonymous donation reads and lists newest rows with validated filters',async()=>{expect((await request(app).get('/api/admin/donations')).status).toBe(401);const cookie=await login();allow();execute.mockResolvedValueOnce([[{id:3,status:'paid'}]]);const response=await request(app).get('/api/admin/donations?status=paid&search=ada&from=2026-01-01&to=2026-01-31').set('Cookie',cookie);expect(response.body).toEqual([{id:3,status:'paid'}]);expect(execute.mock.calls.at(-1)[0]).toMatch(/order by created_at desc,id desc/);allow();expect((await request(app).get('/api/admin/donations?status=unknown').set('Cookie',cookie)).status).toBe(400)});
  it('calculates donation summary server-side and counts only paid money',async()=>{const cookie=await login();allow();execute.mockResolvedValueOnce([[{paid_amount:12500,paid_count:2,created_count:1,failed_count:3}]]);const response=await request(app).get('/api/admin/donations/summary?status=paid').set('Cookie',cookie);expect(response.status).toBe(200);expect(response.body).toEqual({paid_amount:12500,paid_count:2,created_count:1,failed_count:3});expect(execute.mock.calls.at(-1)[0]).toMatch(/sum\(case when status='paid' then amount else 0 end\)/)});
});
