import React,{useEffect,useState}from'react';
import{Navigate,NavLink,useNavigate}from'react-router-dom';
import{imageOk}from'./lib/validation';
import{AdminApiError,adminRequest,publicImageUrl}from'./lib/api';

const messageFor=error=>{
  if(error instanceof AdminApiError){if(error.status===401)return'Your session has expired. Please sign in again.';if(error.status===403)return'This request was rejected by the site security policy.';if(error.status===404)return'The requested record no longer exists.';if(error.status===413)return'The image must be 5 MB or smaller.';if(error.status===429)return'Too many requests. Please try again shortly.';if(error.status===400||error.status===415)return'Please check the submitted details and image type.'}
  return'Unable to complete that request. Please try again.';
};
const expire=error=>{if(error instanceof AdminApiError&&error.status===401&&typeof window!=='undefined')window.dispatchEvent(new Event('admin-unauthorized'));return error};

export function AdminGate({children}){const[state,setState]=useState({loading:true,ok:false,error:false});useEffect(()=>{let active=true;const unauthorized=()=>active&&setState({loading:false,ok:false,error:false});adminRequest('/api/auth/me').then(()=>active&&setState({loading:false,ok:true,error:false})).catch(error=>active&&setState({loading:false,ok:false,error:error.status!==401}));window.addEventListener('admin-unauthorized',unauthorized);return()=>{active=false;window.removeEventListener('admin-unauthorized',unauthorized)}},[]);if(state.loading)return <p className="section">Checking access…</p>;if(state.error)return <section className="section"><p role="alert">Unable to check your session. Please try again.</p><NavLink to="/admin/login">Go to login</NavLink></section>;return state.ok?children:<Navigate to="/admin/login" replace/>}

export function AdminLogin(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),nav=useNavigate();async function go(event){event.preventDefault();setLoading(true);setError('');try{await adminRequest('/api/auth/login',{method:'POST',body:{email,password}});nav('/admin')}catch{setError('Unable to sign in.')}finally{setLoading(false)}}return <section className="section"><h1>Admin login</h1><form onSubmit={go}><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} required/></label><button disabled={loading} className="button">{loading?'Signing in…':'Sign in'}</button>{error&&<p role="alert">{error}</p>}</form></section>}

const Nav=()=> <p className="adminnav"><NavLink to="/admin">Dashboard</NavLink> <NavLink to="/admin/gallery">Gallery</NavLink> <NavLink to="/admin/members">Members</NavLink> <NavLink to="/admin/programs">Programs</NavLink> <NavLink to="/admin/organization">Organization Settings</NavLink> <NavLink to="/admin/messages">Messages</NavLink> <NavLink to="/admin/donations">Donations</NavLink></p>;
const useAdminData=(route,initial)=>{const[data,setData]=useState(initial),[error,setError]=useState('');const load=async()=>{try{setError('');setData(await adminRequest(route))}catch(reason){setError(messageFor(expire(reason)))}};useEffect(()=>{load()},[route]);return{data,error,setError,load}};
const useAdminRows=route=>{const result=useAdminData(route,[]);return{...result,rows:result.data}};

export function AdminHome(){const gallery=useAdminRows('/api/admin/gallery'),members=useAdminRows('/api/admin/members'),programs=useAdminRows('/api/admin/programs'),messages=useAdminRows('/api/admin/contact-messages'),donations=useAdminRows('/api/admin/donations'),[error,setError]=useState(''),nav=useNavigate();async function logout(){try{await adminRequest('/api/auth/logout',{method:'POST'});nav('/admin/login')}catch(reason){setError(messageFor(expire(reason)))}}return <section className="section"><h1>Dashboard</h1><Nav/><button onClick={logout}>Logout</button>{error&&<p role="alert">{error}</p>}{[gallery,members,programs,messages,donations].some(x=>x.error)&&<p role="alert">Unable to load one or more dashboard totals.</p>}<div className="cards">{[['Gallery images',gallery.rows.length],['Members',members.rows.length],['Active members',members.rows.filter(member=>member.active).length],['Programs',programs.rows.length],['Contact messages',messages.rows.length],['Donations',donations.rows.length]].map(([label,count])=><article key={label}><h3>{label}</h3><p>{count}</p></article>)}</div></section>}

function File({value,setValue}){return <label>Image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setValue(event.target.files?.[0]||null)}/>{value&&<><small>{value.name}</small><img className="preview" src={URL.createObjectURL(value)} alt="Preview"/></>}</label>}
const addFile=(form,file)=>{if(file){if(!imageOk(file))throw Error('invalid-image');form.append('image',file)}};
const resetForm=(event,setEdit,setFile,load)=>{setEdit(null);setFile(null);event.currentTarget.reset();load()};

export function AdminGallery(){const{rows,error,load,setError}=useAdminRows('/api/admin/gallery'),[edit,setEdit]=useState(null),[file,setFile]=useState(null);async function save(event){event.preventDefault();try{const data=new FormData(event.currentTarget);data.set('title',String(data.get('title')||'').trim());data.set('description',String(data.get('description')||'').trim());if(!edit){data.set('display_order','0');data.set('active','1')}addFile(data,file);await adminRequest(edit?`/api/admin/gallery/${edit.id}`:'/api/admin/gallery',{method:edit?'PUT':'POST',body:data});resetForm(event,setEdit,setFile,load)}catch(reason){setError(reason.message==='invalid-image'?'Use JPEG, PNG or WebP below 5 MB.':messageFor(expire(reason)))}}async function del(row){if(!confirm(`Delete ${row.title}? This cannot be undone.`))return;try{await adminRequest(`/api/admin/gallery/${row.id}`,{method:'DELETE'});load()}catch(reason){setError(messageFor(expire(reason)))}}return <section className="section"><h1>Gallery management</h1><Nav/><form onSubmit={save}><label>Title<input name="title" required maxLength="160" defaultValue={edit?.title}/></label><label>Description<textarea name="description" maxLength="2000" defaultValue={edit?.description}/></label><label>Event date<input name="event_date" type="date" defaultValue={edit?.event_date||''}/></label><File value={file} setValue={setFile}/><button className="button">{edit?'Save changes':'Add image'}</button></form>{error&&<p role="alert">{error}</p>}<div className="cards">{rows.map(row=><article key={row.id}>{row.image_path&&<img src={publicImageUrl(row.image_path)} alt=""/>}<h3>{row.title}</h3><p>{row.event_date}</p><button onClick={()=>setEdit(row)}>Edit</button> <button onClick={()=>del(row)}>Delete</button></article>)}</div></section>}

export function AdminMembers(){const{rows,error,load,setError}=useAdminRows('/api/admin/members'),[edit,setEdit]=useState(null),[file,setFile]=useState(null);async function save(event){event.preventDefault();try{const data=new FormData(event.currentTarget);data.set('name',String(data.get('name')||'').trim());data.set('bio',String(data.get('bio')||'').trim());data.set('active',data.get('active')==='on'?'1':'0');addFile(data,file);await adminRequest(edit?`/api/admin/members/${edit.id}`:'/api/admin/members',{method:edit?'PUT':'POST',body:data});resetForm(event,setEdit,setFile,load)}catch(reason){setError(reason.message==='invalid-image'?'Use JPEG, PNG or WebP below 5 MB.':messageFor(expire(reason)))}}async function del(row){if(!confirm(`Delete ${row.name}?`))return;try{await adminRequest(`/api/admin/members/${row.id}`,{method:'DELETE'});load()}catch(reason){setError(messageFor(expire(reason)))}}return <section className="section"><h1>Member management</h1><Nav/><form onSubmit={save}><label>Name<input name="name" required maxLength="120" defaultValue={edit?.name}/></label><label>Designation<select name="designation" defaultValue={edit?.designation||'Volunteer'}>{['President','Secretary','Treasurer','Executive Member','Volunteer','Advisor'].map(item=><option key={item}>{item}</option>)}</select></label><label>Biography<textarea name="bio" maxLength="2000" defaultValue={edit?.bio}/></label><label>Display order<input name="display_order" type="number" defaultValue={edit?.display_order||0}/></label><label><input name="active" type="checkbox" defaultChecked={edit?.active??true}/> Active</label><File value={file} setValue={setFile}/><button className="button">{edit?'Save changes':'Add member'}</button></form>{error&&<p role="alert">{error}</p>}<div className="cards">{rows.map(row=><article key={row.id}>{row.photo_path&&<img src={publicImageUrl(row.photo_path)} alt=""/>}<h3>{row.name}</h3><p>{row.designation} · {row.active?'Active':'Inactive'} · #{row.display_order}</p><button onClick={()=>setEdit(row)}>Edit</button> <button onClick={()=>del(row)}>Delete</button></article>)}</div></section>}
export function AdminPrograms(){const{rows,error,load,setError}=useAdminRows('/api/admin/programs'),[edit,setEdit]=useState(null),[file,setFile]=useState(null);async function save(event){event.preventDefault();try{const data=new FormData(event.currentTarget);data.set('title',String(data.get('title')||'').trim());data.set('short_description',String(data.get('short_description')||'').trim());data.set('description',String(data.get('description')||'').trim());data.set('location',String(data.get('location')||'').trim());data.set('active',data.get('active')==='on'?'1':'0');addFile(data,file);await adminRequest(edit?`/api/admin/programs/${edit.id}`:'/api/admin/programs',{method:edit?'PUT':'POST',body:data});resetForm(event,setEdit,setFile,load)}catch(reason){setError(reason.message==='invalid-image'?'Use JPEG, PNG or WebP below 5 MB.':messageFor(expire(reason)))}}async function del(row){if(!confirm(`Delete ${row.title}?`))return;try{await adminRequest(`/api/admin/programs/${row.id}`,{method:'DELETE'});load()}catch(reason){setError(messageFor(expire(reason)))}}return <section className="section"><h1>Program management</h1><Nav/><form onSubmit={save}><label>Title<input name="title" required maxLength="160" defaultValue={edit?.title}/></label><label>Short description<textarea name="short_description" maxLength="500" defaultValue={edit?.short_description}/></label><label>Full description<textarea name="description" maxLength="10000" defaultValue={edit?.description}/></label><label>Location<input name="location" maxLength="255" defaultValue={edit?.location}/></label><label>Start date<input name="start_date" type="date" defaultValue={edit?.start_date||''}/></label><label>End date<input name="end_date" type="date" defaultValue={edit?.end_date||''}/></label><label>Status<select name="status" defaultValue={edit?.status||'upcoming'}>{['upcoming','ongoing','completed'].map(item=><option key={item} value={item}>{item}</option>)}</select></label><label>Display order<input name="display_order" type="number" defaultValue={edit?.display_order||0}/></label><label><input name="active" type="checkbox" defaultChecked={edit?.active??true}/> Active</label><File value={file} setValue={setFile}/><button className="button">{edit?'Save changes':'Add program'}</button></form>{error&&<p role="alert">{error}</p>}<div className="cards">{rows.map(row=><article key={row.id}>{row.image_path&&<img src={publicImageUrl(row.image_path)} alt=""/>}<h3>{row.title}</h3><p>{row.status} · {row.active?'Active':'Inactive'} · #{row.display_order}</p><button onClick={()=>setEdit(row)}>Edit</button> <button onClick={()=>del(row)}>Delete</button></article>)}</div></section>}
const organizationFields={organization:[['organization_name','NGO Name','text',160,true],['tagline','Tagline','text',255],['short_description','Short Description','textarea',1000]],contact:[['primary_email','Primary Email','email',254,true],['secondary_email','Secondary Email','email',254],['primary_phone','Primary Phone','tel',30,true],['secondary_phone','Secondary Phone','tel',30],['whatsapp_number','WhatsApp Number','tel',30]],address:[['address','Address','textarea',500],['city','City','text',120],['state','State','text',120],['postal_code','PIN Code','text',20],['google_maps_url','Google Maps URL','url',500]],social:[['facebook_url','Facebook','url',500],['instagram_url','Instagram','url',500],['youtube_url','YouTube','url',500],['linkedin_url','LinkedIn','url',500]],website:[['website_url','Website URL','url',500]]};
const emptyOrganization=Object.fromEntries(Object.values(organizationFields).flat().map(([name])=>[name,'']));
export function AdminOrganization(){const settings=useAdminData('/api/admin/organization',{}),[form,setForm]=useState(emptyOrganization),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');useEffect(()=>setForm({...emptyOrganization,...settings.data}),[settings.data]);const change=event=>setForm(current=>({...current,[event.target.name]:event.target.value}));async function save(event){event.preventDefault();setSaving(true);setNotice('');try{const saved=await adminRequest('/api/admin/organization',{method:'PUT',body:form});setForm({...emptyOrganization,...saved});setNotice('Organization settings saved.')}catch(reason){settings.setError(messageFor(expire(reason)))}finally{setSaving(false)}}const section=(title,fields)=><fieldset key={title}><legend>{title}</legend>{fields.map(([name,label,type,max,required])=><label key={name}>{label}{type==='textarea'?<textarea name={name} value={form[name]||''} onChange={change} maxLength={max}/>:<input name={name} type={type} value={form[name]||''} onChange={change} maxLength={max} required={required}/>}</label>)}</fieldset>;return <section className="section"><h1>Organization Settings</h1><Nav/><form onSubmit={save}>{section('Organization',organizationFields.organization)}{section('Contact details',organizationFields.contact)}{section('Address',organizationFields.address)}{section('Social media',organizationFields.social)}{section('Website',organizationFields.website)}<button disabled={saving} className="button">{saving?'Saving…':'Save Changes'}</button>{settings.error&&<p role="alert">{settings.error}</p>}{notice&&<p role="status">{notice}</p>}</form></section>}

export function AdminMessages(){const{rows,error}=useAdminRows('/api/admin/contact-messages');return <section className="section"><h1>Contact messages</h1><Nav/>{error&&<p role="alert">{error}</p>}{rows.map(row=><article className="message" key={row.id}><h3>{row.subject}</h3><p>{row.name} · {row.email} · {row.mobile}</p><p>{row.message}</p></article>)}</section>}
export function AdminDonations(){const[filters,setFilters]=useState({status:'',search:'',from:'',to:''});const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value));const suffix=query.toString()?`?${query}`:'';const list=useAdminRows(`/api/admin/donations${suffix}`),summary=useAdminData(`/api/admin/donations/summary${suffix}`,{});const change=event=>setFilters(current=>({...current,[event.target.name]:event.target.value}));const rupees=value=>`₹${(Number(value||0)/100).toFixed(2)}`;return <section className="section"><h1>Donations</h1><Nav/><form><label>Status<select name="status" value={filters.status} onChange={change}><option value="">All statuses</option>{['created','paid','failed'].map(item=><option key={item}>{item}</option>)}</select></label><label>Donor search<input name="search" value={filters.search} onChange={change} maxLength="120"/></label><label>From<input name="from" type="date" value={filters.from} onChange={change}/></label><label>To<input name="to" type="date" value={filters.to} onChange={change}/></label></form>{(list.error||summary.error)&&<p role="alert">{list.error||summary.error}</p>}<div className="cards"><article><h3>Received</h3><p>{rupees(summary.data.paid_amount)} · {summary.data.paid_count||0} paid</p></article><article><h3>Pending</h3><p>{summary.data.created_count||0}</p></article><article><h3>Failed</h3><p>{summary.data.failed_count||0}</p></article></div>{list.rows.map(row=><article className="message" key={row.razorpay_order_id}><strong>{row.donor_name}</strong><p>{row.donor_email} · {row.donor_mobile}</p><p>{rupees(row.amount)} {row.currency} · {row.status} · {new Date(row.created_at).toLocaleString()}</p><small>Order: {row.razorpay_order_id} {row.razorpay_payment_id?` · Payment: ${row.razorpay_payment_id}`:''}</small></article>)}</section>}
